version: 2
updates:
  - package-ecosystem: "npm"
    commit-message:
      prefix: "[deps] "
      prefix-development: "[dev-deps] "
    directory: "/"
    groups:
      dependencies:
        dependency-type: "production"
      devDependencies:
        dependency-type: "development"
    reviewers:
      - "ckwalsh"
    schedule:
      interval: "weekly"
