version: 2
updates:
  - package-ecosystem: "npm"
    assignees:
      - "ckwalsh"
    commit-message:
      prefix: "dependencies"
      prefix-development: "devDependencies"
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: "weekly"
